FaixaEtaria/Models/Pessoa.cs
using FaixaEtaria.Validação;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FaixaEtaria.Models
{
    public class Pessoa
    {
        public int PessoaId { get; set; }

        [Remote("UsuarioExisteAsync", "Pessoas")]
        public string Nome { get; set; }

        [Adultos]
        public int Idade { get; set; }
    }
}

FaixaEtaria/Controllers/PessoasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FaixaEtaria.Models;

namespace FaixaEtaria.Controllers
{
    public class PessoasController : Controller
    {
        private readonly PessoaContexto _context;

        public PessoasController(PessoaContexto context)
        {
            _context = context;
        }

        public async Task<JsonResult> UsuarioExisteAsync(string nome)
        {
            if (await _context.Pessoas.AnyAsync(x => x.Nome == nome))
                return Json("Usuário já existe");

            return Json(true);
        }

        // GET: Pessoas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pessoas.ToListAsync());
        }

        // GET: Pessoas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoas
                .FirstOrDefaultAsync(m => m.PessoaId == id);
            if (pessoa == null)
            {
                return NotFound();
            }

            return View(pessoa);
        }

        // GET: Pessoas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pessoas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PessoaId,Nome,Idade")] Pessoa pessoa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pessoa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }

        // GET: Pessoas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoas.FindAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }
            return View(pessoa);
        }

        // POST: Pessoas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PessoaId,Nome,Idade")] Pessoa pessoa)
        {
            if (id != pessoa.PessoaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pessoa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoaExists(pessoa.PessoaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }

        // GET: Pessoas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pessoa = await _context.Pessoas
                .FirstOrDefaultAsync(m => m.PessoaId == id);
            if (pessoa == null)
            {
                return NotFound();
            }

            return View(pessoa);
        }

        // POST: Pessoas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pessoa = await _context.Pessoas.FindAsync(id);
            _context.Pessoas.Remove(pessoa);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PessoaExists(int id)
        {
            return _context.Pessoas.Any(e => e.PessoaId == id);
        }
    }
}

FaixaEtaria/ViewComponents/AdolescenteViewComponent.cs
using FaixaEtaria.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FaixaEtaria.ViewComponents
{
    public class AdolescenteViewComponent : ViewComponent
    {
        private readonly PessoaContexto _pessoaContexto;

        public AdolescenteViewComponent(PessoaContexto pessoaContexto)
        {
            _pessoaContexto = pessoaContexto;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _pessoaContexto.Pessoas.Where(x => x.Idade < 18).ToListAsync());
        }
    }
}

FaixaEtaria/ViewComponents/AdultosViewComponent.cs
using FaixaEtaria.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FaixaEtaria.ViewComponents
{
    public class AdultosViewComponent : ViewComponent
    {
        private readonly PessoaContexto _pessoaContexto;

        public AdultosViewComponent(PessoaContexto pessoaContexto)
        {
            _pessoaContexto = pessoaContexto;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _pessoaContexto.Pessoas.Where(x => x.Idade >= 18 && x.Idade < 60).ToListAsync());
        }
    }
}

FaixaEtaria/ViewComponents/IdososViewComponent.cs
using FaixaEtaria.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FaixaEtaria.ViewComponents
{
    public class IdososViewComponent : ViewComponent
    {
        private readonly PessoaContexto _pessoaContexto;

        public IdososViewComponent(PessoaContexto pessoaContexto)
        {
            _pessoaContexto = pessoaContexto;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(await _pessoaContexto.Pessoas.Where(x => x.Idade >= 60).ToListAsync());
        }
    }
}

FaixaEtaria/Views/Pessoas/Adolescentes.cshtml
@model IEnumerable<FaixaEtaria.Models.Pessoa>


@if (Model.Any(x => x.Idade < 18))
{
    <div class="panel panel-default">
        <div class="panel-heading">Adolescentes cadastrados (@Model.Count(x => x.Idade < 18))</div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nome)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Idade)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
            @foreach (var item in Model)
            {
                @if (item.Idade < 18)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Idade)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.PessoaId">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.PessoaId">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.PessoaId">Delete</a>
                        </td>
                    </tr>
                }
            }
                </tbody>
            </table>
        </div>
</div>
}

FaixaEtaria/Views/Pessoas/Adultos.cshtml
@model IEnumerable<FaixaEtaria.Models.Pessoa>


@if (Model.Any(x => x.Idade >= 18 && x.Idade < 60))
{
    <div class="panel panel-default">
        <div class="panel-heading">Adultos cadastrados (@Model.Count(x => x.Idade > 18 && x.Idade < 60))</div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nome)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Idade)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
            @foreach (var item in Model)
            {
                @if (item.Idade >= 18 && item.Idade < 60)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Idade)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.PessoaId">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.PessoaId">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.PessoaId">Delete</a>
                        </td>
                    </tr>
                }
            }
                </tbody>
            </table>
        </div>
</div>
}

FaixaEtaria/Views/Pessoas/Create.cshtml
@model FaixaEtaria.Models.Pessoa

@{
    ViewData["Title"] = "Create";
}

<h2>Cadastrar</h2>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FaixaEtaria/Views/Pessoas/Delete.cshtml
@model FaixaEtaria.Models.Pessoa

@{
    ViewData["Title"] = "Delete";
}

<h2>Excluir</h2>

<h3>Confirmar exclusão?</h3>
<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PessoaId" />
        <input type="submit" value="Excluir" class="btn btn-default" /> |
        <a asp-action="Index">Voltar à lista</a>
    </form>
</div>

FaixaEtaria/Views/Pessoas/Details.cshtml
@model FaixaEtaria.Models.Pessoa

@{
    ViewData["Title"] = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PessoaId">Editar</a> |
    <a asp-action="Index">Voltar à lista</a>
</div>

FaixaEtaria/Views/Pessoas/Edit.cshtml
@model FaixaEtaria.Models.Pessoa

@{
    ViewData["Title"] = "Edit";
}

<h2>Editar</h2>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PessoaId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FaixaEtaria/Views/Pessoas/Idosos.cshtml
@model IEnumerable<FaixaEtaria.Models.Pessoa>


@if (Model.Any(x => x.Idade > 60))
{
    <div class="panel panel-default">
        <div class="panel-heading">Idosos cadastrados (@Model.Count(x => x.Idade > 60))</div>
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nome)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Idade)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
            @foreach (var item in Model)
            {
                @if (item.Idade > 60)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Idade)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.PessoaId">Editar</a> |
                            <a asp-action="Details" asp-route-id="@item.PessoaId">Detalhes</a> |
                            <a asp-action="Delete" asp-route-id="@item.PessoaId">Excluir</a>
                        </td>
                    </tr>
                }
            }
                </tbody>
            </table>
        </div>
</div>
}

FaixaEtaria/Views/Pessoas/Index.cshtml
@model IEnumerable<FaixaEtaria.Models.Pessoa>

@{
    ViewData["Title"] = "Index";
}

<h2>Cadastrados (@Model.Count())</h2>

<p>
    <a asp-action="Create" class="btn btn-primary">Cadastrar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Idade)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.PessoaId">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.PessoaId">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.PessoaId">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@await Component.InvokeAsync("Adolescente")
@await Component.InvokeAsync("Adultos")
@await Component.InvokeAsync("Idosos")